[ci] Fix param casing
Casing was incorrect.

Tested by running locally with a PAT.

```
$ scripts/release/download-experimental-build.js --commit=1a664827287b3c4f18da39f4394fb63c9beb0bb3
Command failed: gh attestation verify artifacts_combined.zip --repo=facebook/react

Error: failed to fetch attestations from facebook/react: HTTP 404: Not Found (https://api.github.com/repos/facebook/react/attestations/sha256:23d05644f9e49e02cbb441e3932cc4366b261826e58ce222ea249a6b786f0b5f?per_page=30)
`gh attestation verify artifacts_combined.zip --repo=facebook/react` (exited with error code 1)

$ scripts/release/download-experimental-build.js --commit=1a664827287b3c4f18da39f4394fb63c9beb0bb3 --noVerify
⠼ Downloading artifacts from GitHub for commit 1a664827287b3c4f18da39f4394fb63c9beb0bb3)  5%                  0.1m, estimated 1.6m
✓ Downloading artifacts from GitHub for commit 1a664827287b3c4f18da39f4394fb63c9beb0bb3) 9.5 secs
An experimental build has been downloaded!

You can download this build again by running:
  scripts/download-experimental-build.js --commit=1a664827287b3c4f18da39f4394fb63c9beb0bb3
```